# Generated by Django 4.2.1 on 2023-06-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('idInstalacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='assets/img/instalaciones')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Instalacion',
                'verbose_name_plural': 'Instalaciones',
                'db_table': 'instalaciones',
            },
        ),
    ]
