# Generated by Django 4.2.1 on 2023-06-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalaciones',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='instalaciones/'),
        ),
    ]
