# Generated by Django 4.2.1 on 2023-06-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instalaciones', '0002_alter_instalaciones_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instalaciones',
            name='costo',
        ),
    ]
