# Generated by Django 4.2.1 on 2023-05-31 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CarritoProductos',
                'verbose_name_plural': 'CarritosProductos',
                'db_table': 'CarritoProductos',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarritoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ecommerce.carritoproductos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
            ],
            options={
                'verbose_name': 'DetalleCarritoProducto',
                'verbose_name_plural': 'DetallesCarritosProductos',
                'db_table': 'DetalleCarritoProducto',
            },
        ),
    ]
