# Generated by Django 4.2.1 on 2023-06-13 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_factura'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.RemoveField(
            model_name='carritoproductos',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='detallecarritoproductos',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='detallecarritoproductos',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.producto'),
        ),
        migrations.AlterModelTable(
            name='factura',
            table='Factura',
        ),
    ]
