# Generated by Django 4.2.1 on 2023-06-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_alter_producto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='carrito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.carritoproductos'),
        ),
    ]
