# Generated by Django 4.2.1 on 2023-06-02 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instalaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False)),
                ('fechaHora', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instalaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalaciones_usuario', to='instalaciones.instalaciones')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
    ]
