# Generated by Django 4.2.1 on 2023-06-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
