# Generated by Django 4.2.1 on 2023-06-02 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_alter_reserva_costo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='costo',
        ),
    ]
