# Generated by Django 4.2.1 on 2023-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_reserva_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10),
        ),
    ]
