# Generated by Django 4.2.1 on 2023-06-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_reserva_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default='08:00'),
        ),
    ]
